on: [push]

jobs:
  build_unixtimestamps:
    runs-on: ubuntu-latest
    name: Build Unix Timestamps
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/ukd1/unixtimestamps:latest
          platforms: linux/amd64,linux/arm64
