on: [push]

jobs:
  build_unixtimestamps:
    runs-on: ubuntu-latest
    name: Build Unix Timestamps
    steps:
      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ghcr.io/ukd1/unixtimestamps:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/ukd1/unixtimestamps:buildcache
          cache-to: type=registry,ref=ghcr.io/ukd1/unixtimestamps:buildcache,mode=max
